# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52ebd870e199fd104f6a2aa91d16848ca86c63696296730ffd262bc91b4f5ac232144f074d2ecf7bd7926565d94792dde9744ddf1fce3033cb7b7aa51751af73

test:
  secret_key_base: b3eb731e9a390c3045e765c72fd4427b2923eb25f3efceb2b6243e69e4fa65b4996aca766520fd7ee9447191a97d16cbf18063616c1ba25a1531ba1849db15d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
